name: demo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase packages - ALL upgraded to compatible versions
  firebase_core: ^3.13.1  # Required by firebase_app_check
  firebase_analytics: ^11.4.4
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_database: ^11.3.4
  firebase_storage: ^12.4.4
  firebase_messaging: ^15.2.4
  firebase_crashlytics: ^4.3.4
  firebase_remote_config: ^5.4.2
  firebase_performance: ^0.10.1+4
  firebase_in_app_messaging: ^0.8.1+4
  firebase_app_check: ^0.3.2+4

  # Other packages
  fl_chart: ^1.0.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.3.0
  image_picker: ^1.1.2
  convert: ^3.1.2
  shared_preferences: ^2.5.2
  fluttertoast: ^8.2.2
  flutter_animate: ^4.5.2
  async: ^2.12.0
  fake_async: ^1.3.2
  leak_tracker: ^11.0.1
  material_color_utilities: ^0.11.1
  vm_service: ^14.3.1
  google_fonts: ^6.2.1
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  cached_network_image: ^3.3.0
  video_player: ^2.8.0
  intl: ^0.20.2
  path: ^1.8.3
  liquid_progress_indicator: ^0.4.0
  uuid: ^4.3.3
  logger: ^2.5.0
  flutter_dotenv: ^5.1.0
  permission_handler: ^12.0.0+1
  file_picker: ^10.1.9
  font_awesome_flutter: ^10.4.0
  location: ^8.0.0
  google_maps_flutter: ^2.2.0
  url_launcher: ^6.1.12

  # TensorFlow Lite - compatible versions
  tflite_flutter: ^0.9.5
  tflite_flutter_helper: ^0.2.0
  syncfusion_flutter_charts: ^31.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.11.0

flutter_launcher_icons:
  android: true
  image_path: "assets/1024.png"

flutter:
  uses-material-design: true
  assets:
    - assets/1024.png
    - assets/mpesa.png
    - assets/ecocash.png
    - assets/fnb.png
    - assets/standard.png
    - assets/netbank.png
    - images/water.jpg
    - images/water2.jpg
    - images/water3.jpg
    - .env
